### ISSUE TITLE
Example evaluation code error

### ISSUE THREAD

**Issue by ShichangZh** [wanyu-lin/ICML2021-Gem#4]
Hi Wanyu,

Thank you for opening your source code. I followed the instruction to reproduce the result, but the example evaluation code gave me an error. May I ask how should this be fixed?

I closely followed the preparation, distillation, and training code. Then when I ran the following example

```
python test_explained_adj_graph.py --graph-mode --dataset=NCI1 --exp_out=nci1_dc_top20 --distillation=nci1_dc_top20 --top_k=15 --test_out=nci1_dc_top20_top15
```
and I got 

<img width="1416" alt="Screen Shot 2022-04-07 at 12 39 45 PM" src="https://user-images.githubusercontent.com/21331572/162283836-2a26de7e-f3af-4e9a-bbb7-d85870d32f2c.png">

Seems like there is some ckpt that was generated from the training step that is missing? However, in the training script I didn't find where this was generated.

**Comment by haolanut** [comment]
Hi, 

did you train **_Gem_** and generate explanation by running following command: `python test_explained_adj_graph.py --graph-mode --dataset=NCI1 --exp_out=nci1_dc_top20 --distillation=nci1_dc_top20 --top_k=15 --test_out=nci1_dc_top20_top15`

**Comment by ShichangZh** [comment]
Thank you for the quick response. Yes. The commend you provided is the one given me the error in the screenshot. I just reran it one more time to confirm. 

I trained the model with the command below and it worked, I saw 300 epochs of training outputs.
```
python explainer_gae_graph.py --distillation=nci1_dc_top20 --output=nci1_dc_top20 --dataset=NCI1 --gpu -b 128 --weighted --gae3 --loss=mse --early_stop --graph_labeling --train_on_positive_label --epochs=300 --lr=0.01
```

Also, I noticed the training generated many csv files as below
```
gem/explanation/nci1_dc_top20/graph_idx_3692_label.csv
```

but seems like the evaluation was looking for ckpts
```
explanation/gnnexp/NCI1_base_h20_o20_explain/masked_adj_node_idx_0graph_idx_3692.ckpt'
```
and they are missing.

**Comment by haolanut** [comment]
`explanation/gnnexp/NCI1_base_h20_o20_explain/masked_adj_node_idx_0graph_idx_3692.ckpt` is the explanation generated by GNNExplainer.
You can extract it from zip by running `unzip gnnexp_explanation.zip`, or generate the explanation by following the instruction in [preparation.md](preparation.md).

**Comment by ShichangZh** [comment]
Thank you so much! The evaluation code is working now. I thought the evaluation script is only for gem and the baselines were in separate scripts. Turns out I misunderstood. Closing the issue now.
