### ISSUE TITLE
model re-training does not re-create required ckpt files

### ISSUE THREAD

**Issue by simoons95** [wanyu-lin/ICML2021-Gem#5]
Hello,

I tried to run the repo without using the pre-registered checkpoints (zip files), and I was unable to do so.
Some files that are in the zip are not under the same name (e.g. `syn1_base_h20_o20_explain/masked_adj_node_idx_520graph_idx_0.npy` is rather at `masked_adj_syn1_base_h20_o20_explainnode_idx_520graph_idx_-1.npy`), while others are not created at all (`syn1_base_h20_o20_explain/masked_adj_node_idx_520graph_idx_0.ckpt`).
This prevents me from running the explanations.
How can I fix this?

Have a nice day!

**Comment by haolanut** [comment]
Hi @simoons95,

How are you?
Did you apply `gnnexp.patch` before training and generating explanation results for GNNExplainer? We change the explanation output path and save some necessary information for evaluation in the `.ckpt` file. So you need to patch the original implementation of GNNExplainer to reproduce the experiments.

**Comment by simoons95** [comment]
Indeed, we forgot to run it. Everything is running fine now, many thanks!
